### ISSUE TITLE
Diamond test suite fails overall test suite

### ISSUE THREAD

**Issue by marceljay** [closerdao/proof-of-presence#40]
When trying to run the unit tests, the suite fails due an issue in the Diamond library:

```
1) BookingMapLib
       buildTimestamp:

      AssertionError: expected 1 to equal 365
      + expected - actual

      -1
      +365
      
      at /Users/mav/dev/eth/TDF-contracts/test/diamond/libraries/BookingMapLib.test.ts:129:34
      at step (test/diamond/libraries/BookingMapLib.test.ts:44:23)
      at Object.next (test/diamond/libraries/BookingMapLib.test.ts:25:53)
      at fulfilled (test/diamond/libraries/BookingMapLib.test.ts:16:58)

```

This should be corrected in order to work on the unit tests.

**Comment by arturictus** [comment]
The CI is working, so I would deprioritize this issue

**Comment by arturictus** [comment]
related to #46
